[supervisord]

nodaemon=true

[program:nginx]
command=/usr/sbin/nginx -g "daemon off;"
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:php-fpm]
command=php-fpm7.4
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
priority=1

[program:cron]
command=/cron-startup.sh
autostart=true
autorestart=unexpected
exitcodes=0

[program:laravel-queue]
command=php /usr/share/nginx/ibim-license-management/artisan queue:work --tries=1 --timeout=1200
numprocs=1
autostart=true
autorestart=true
user=root
priority=1

# [program:laravel-queue-high]
# command=php /usr/share/nginx/appyhours-backend/artisan queue:work --tries=1 --queue=high --timeout=1200
# numprocs=1
# autostart=true
# autorestart=true
# user=root
# priority=1